### ISSUE TITLE
armhf support for 5.3

### ISSUE THREAD

**Issue by xaeroolj** [futurejones/swift-arm64#10]
Hello, im new with Raspberry and I currently run raspbian os on zero w board. (deb 10 armhf)  
Last version of swift available is 5.1.5. 
Will you support armhf with new releases? Or need switch to other os?

Regards, Roman

**Comment by futurejones** [comment]
@xaeroolj At the moment if you want to run a Swift version newer than 5.1.5 you will need to use a Raspberry Pi that will run a 64bit(arm64) OS.  This can be any Pi 3 or Pi 4 model.
Unfortunately the Pi Zero is only 32bit(armhf). There is work being done to try and get Swift 5.2+ on 32bit(armhf) but at the moment there are no working builds.

**Comment by xaeroolj** [comment]
Thanks for a clear and  quick response.

I am close issue now.
Regards, Roman.
