### ISSUE TITLE
Support Ubuntu 20.10 (Groovy Gorilla)

### ISSUE THREAD

**Issue by ikester** [futurejones/swift-arm64#11]
I just got `swift` 5.3.1 working on Ubuntu 20.10 by downloading the repo config script and passing `os=ubuntu dist=focal` when running it. It would be great to have a "native" repo available for Ubuntu 20.10.

**Comment by futurejones** [comment]
@ikester, I am already working on it. I have put in a request to PackageCloud to add Ubuntu 20.10 to their list of available distributions. As soon as this is done I will upload versions for 20.10 Groovy.

**Comment by smumryak** [comment]
Just wanted to comment on this. I'm using this build on 20.10 on raspberry pi 4. It works out of the box, but you just need to tell aptitute that you know what you are doing and it will be installed correctly.

**Comment by karwa** [comment]
Hey @futurejones - firstly, thanks for maintaining this. 

The recent 5.4 release seems to have forgotten about groovy. Is it possible for swift to "get its groove back"? 😄 Thanks.

**Comment by futurejones** [comment]
🦍 Groovy is back for Swift 5.4 
https://packagecloud.io/app/swift-arm/release/search?dist=ubuntu%2Fgroovy
https://github.com/futurejones/swift-arm64/releases/tag/v5.4-RELEASE

_Note: If you are installing using a tar.gz file use the Ubuntu 20.04 version._
