### ISSUE TITLE
[Feature request] Swift Foundation

### ISSUE THREAD

**Issue by duyquang91** [futurejones/swift-arm64#15]
Is it possible to build Swift Foundation & ship to swiftlang together?

**Comment by futurejones** [comment]
@duyquang91  Foundation is already included in the swiftlang package. 
As well as all the other core libraries - https://swift.org/core-libraries/

**Comment by duyquang91** [comment]
@futurejones thank! How about the sourcekit-lsp?

**Comment by futurejones** [comment]
@duyquang91 sourcekit-lsp server is included in the toolchain.
For info on Editor integration please read - https://github.com/apple/sourcekit-lsp/blob/main/Editors/README.md
