### ISSUE TITLE
Recommended setup for VSCode debugging

### ISSUE THREAD

**Issue by scottandrew** [futurejones/swift-arm64#16]
I have this installed on a Raspberry Pi running Ubuntu 20.10. What is the recommended setup for 5.3.3 to enable debugging? I can't seem to get any of the LLVM plugins to work.

**Comment by futurejones** [comment]
@scottandrew the best place to get info on this would be the swift-arm slack team.
You can join the swift-arm slack here - https://launchpass.com/swift-arm
