### ISSUE TITLE
update swiftlang packge for latest version (or at least 5.2+) for raspberrypi/armhf platform

### ISSUE THREAD

**Issue by jdg71nl** [futurejones/swift-arm64#17]
How come the latest build package for swiftlang for the raspberrypi/armhf platform and raspbian/buster distribution is 5.1.5 ?

This is the latest package I can find on the https://packagecloud.io/swift-arm/release  repo:
swiftlang_5.1.5-1_armhf.deb

While the latest packages on this repo for other arch/distro is: 5.4.x

Is that because of some dependency problems or alike?

Can you please build the latest version?

Or show me how (although I have never build such myself before) ?

```
> apt search swiftlang
swiftlang/buster 5.1.5-1 armhf
  Swift 5.1.5 RELEASE for raspbian/buster - All RaspberryPi's: Classic, Zero, 2, 3, 4 - Swift-Arm Community Release.
```

**Comment by futurejones** [comment]
@jdg71nl armv7/armhf builds have been stuck on 5.1.5 for a while now. If you want info on armhf builds please see the [buildSwiftOnARM](https://github.com/uraimo/buildSwiftOnARM) repo. This repo covers arm64/aarch64 only.
In particular check this issue https://github.com/uraimo/buildSwiftOnARM/issues/66 which outlines some of the current problems with armv7/armhf (32 bit) builds.

**Comment by colemancda** [comment]
@futurejones: @buttaface seems to have the entire compiler suite working on Android Armv7 (In Termux), we should look into his work to see if we can achieve the same for Linux Armv7.

@jdg71nl You can use the cross compiled runtime in the meanwhile in this repo as `swiftlang-slim` and use https://github.com/colemancda/swift-armv7 to cross compile from Linux or macOS
