### ISSUE TITLE
Pi 3 Image Blocks mmap to Peripheral Registers By Default

### ISSUE THREAD

**Issue by Kaiede** [futurejones/swift-arm64#2]
Just as an FYI, the Debian Buster image is using a kernel compiled with CONFIG_IO_STRICT_DEVMEM set. This blocks tools like pigpio or SwiftyGPIO from accessing parts of the GPIO registers using /dev/mem. I'm interested in the PWM registers myself. 

Adding "iomem=relaxed" to /boot/firmware/cmdline.txt is enough to get around this.

Might be worth calling out in the readme, for the random person like me doing hardware access wanting to test with the image to compare Raspbian and an ARM64 image. It could be added to the image itself, but I'm not sure it's worth the extra effort here.

**Comment by Kaiede** [comment]
Yeah, I figured I'd just drop a line. I'm honestly surprised at how well things seem to be working. Better than the armv7 4.1.2 build. Only had one typecasting issue that works with 4.1.2 on Ubuntu on x86, which I think is really just a Swift bug. 

Would you say it is probably likely that arm64 will be easier to keep running going forward compared to arm32? It seems like 4.2 already mostly builds? 

I'm mostly trying to plan for the future, as so many packages are Swift 4 only, or aren't receiving Swift 3 updates anymore. But now I have an aquarium light controller built in Swift to maintain.

**Comment by futurejones** [comment]
Swift on Arm64 should be fully supported moving forward. The 4.2 and master branches are building ok on Ubuntu 16.04. The only real issue at the moment is the Swift Package Manager which builds on 4.1 but not on 4.2.
Ubuntu 18.04 is proving to be more troublesome. I have had no success building swift from scratch on 18.04.

**Comment by Kaiede** [comment]
> Swift on Arm64 should be fully supported moving forward. The 4.2 and master branches are building ok on Ubuntu 16.04. The only real issue at the moment is the Swift Package Manager which builds on 4.1 but not on 4.2.

That's a shame about the Package Manager, but it at least sounds like it's a more optimistic situation compared to 4.x on arm32 at the moment. I guess I should decide if I should keep supporting the Pi Zero or not in the coming months. Oh well. 

> Ubuntu 18.04 is proving to be more troublesome. I have had no success building swift from scratch on 18.04.

That's a bit more worrisome with 4.2 getting official snapshots now.

I kinda wish I had time to dig into some of this stuff and help unblock. Unfortunately, my free time is mostly sunk in getting this project completed.

**Comment by buttaface** [comment]
>the Swift Package Manager which builds on 4.1 but not on 4.2

What exactly is the problem and is it still not building? I ask because I've been building Swift natively on Android AArch64, apple/swift#23208, and the last remaining piece that isn't working is building the package manager. The swift compiler segfaults when trying [to interpret the Package.swift for the package manager itself and generate a JSON description from it](https://github.com/apple/swift-package-manager/blob/d001fc6fc431ef30b8e1af211914e10a1cb9725f/Sources/PackageLoading/ManifestLoader.swift#L419).

Same problem for you or something else?
