### ISSUE TITLE
Please add build scripts,

### ISSUE THREAD

**Issue by savoptik** [futurejones/swift-arm64#21]
I'm trying to build a swift for raspberry pi, because I did not find ready-made builded of versions from 5.3 and higher. but I can't build any version, I tried to build 5.3, 5.4.2.
It would be great if there were ready-made scripts that would allow you to independently build the swift of the desired version.

**Comment by futurejones** [comment]
@savoptik what OS are you trying to build for? 
If you running the standard Raspbian/Buster or Raspberry PI OS these are both 32bit systems and you need to go to https://github.com/uraimo/buildSwiftOnARM for build information and releases.

**Comment by savoptik** [comment]
Yes, I am using raspberryOS, thanks, I will take a look at this link. :-)
Отправлено с Mac
