### ISSUE TITLE
@objc should simply be ignored.

### ISSUE THREAD

**Issue by austintatiousness** [futurejones/swift-arm64#22]
In the more recent builds, `@objc` is no longer simply ignored. `@objc` should be ignored instead of throwing `error: Objective-C interoperability is disabled` regardless of the availability of Objective-C.

Since swift doesn't support the following: 
```
#if os(iOS) 
@objc
#endif
```
we would have to duplicate all the functions/properties simply to ignore @objc. 

```
#if os(Apple…)
@objc
public func invokeAction() {
//do a lot of stuff
//and do lots more stuff
}
#else
public func invokeAction() {
//do a lot of stuff
//and do lots more stuff
}
#endif
```

I tried `-enable-objc-interop`, but either it is no longer functional or I don't understand how it should be used.

**Comment by futurejones** [comment]
@austintatiousness, you would be better asking this question on https://forums.swift.org/ as the work here is related to the building of the Swift toolchains on arm64 not issues with the swift language itself.
Also some more detailed information on which which platform and what version of swift you are using will help people find an answer for you.
I'm sure someone on the swift forum will be able to help you.

**Comment by austintatiousness** [comment]
You helped me realize I was very mistaken (thinking it was only only in the arm version) and that I was using an older build on Ubuntu x86_64, and you're right, this same behaviour is present on intel builds too.
