### ISSUE TITLE
Is there a buildroot package available?

### ISSUE THREAD

**Issue by AndreasPantle** [futurejones/swift-arm64#23]
Hey, does someone run Swift with a own compiled Busybox/Buildroot Linux? Maybe to share the experience?

**Comment by colemancda** [comment]
@AndreasPantle here is a buildroot external layer I've developed https://github.com/MillerTechnologyPeru/buildroot-swift , we also have Yocto support https://github.com/MillerTechnologyPeru/meta-swift
