### ISSUE TITLE
Ubuntu 16.04 aarch64 latest Swift (5.5) toolchain not available

### ISSUE THREAD

**Issue by gazsiazasz** [futurejones/swift-arm64#24]
Hi Jones,

Is there a way to have this package version built as well as the others? This was the version what I could make work on my Synology NAS. It is shipped with quite old libc, libstdc++ libs and all it's lib stuff is quite old.
(I know that DSM 7.0 shipped with newer GPL stuff (and dropped a lot of useful features), but it is quite a memory hog, and they already dropped support for arm nas-es since the latest version. So there is no point upgrade the OS.)

The other way I am thinking of if is there a way to cross-compile Swift on x64 to aarch64?
It takes ages on a normal machine, but on some weak arm cpu is like years to compile

Thanks

**Comment by futurejones** [comment]
Hi @gazsiazasz,
I have looked at building Ubuntu 16.04 aarch64 5.5.2 versions but it is not possible at the moment due to lack of resources.  

There is a good cross-compile project that may help you - https://github.com/CSCIX65G/SwiftCrossCompilers

**Comment by gazsiazasz** [comment]
Isn't this project also needs the Swift binaries compiled for 16.04 Ubuntu?
I meant I would compile the Swift toolchain, if it is possible to cross compile them from their sources.
