### ISSUE TITLE
swift code builds fail on external storage

### ISSUE THREAD

**Issue by darkoverlordofdata** [futurejones/swift-arm64#25]
I've installed swiftlang-5.5.2-debian-11-release-aarch64-01-2021-12-4.tar.gz on my chromebook. In case you're not familiar, ChromeOS can install a debian instance in a kvm. 

Swift works great when I have my source code in internal storage, I can even create gui programs using TokamakGTK.
But because I only have 64gb to share between Chrome and Linux, I only allocate 10 gb to linux, and then most of my linux files, including projects, are kept on a 128gb usb. This works fine for other languages, such as cpp, but not for swift

So for example, when I:
```
cd /mnt/chromeos/removable/deimos/
mkdir HelloWorldSPM
cd HelloWorldSPM
swift package init --type executable
swift build
error: unable to attach DB: error: accessing build database "/mnt/chromeos/removable/deimos/HelloWorldSPM/.build/aarch64-unknown-linux-gnu/build.db": disk I/O error
```

**Comment by futurejones** [comment]
@darkoverlordofdata ,I haven't seen a problem like that before. You could try asking for help at the [swift-arm](https://launchpass.com/swift-arm) Slack channel.

**Comment by darkoverlordofdata** [comment]
Thanks, I'll give that a try. I'm not blocked, I can still use swift on internal storage. It's just a bit cramped.
