### ISSUE TITLE
Fix for libtensorflow and libtensorflow_framework not being included in builds

### ISSUE THREAD

**Issue by BradLarson** [futurejones/swift-arm64#5]
First off, thank you for the great work in pulling this all together in one place. It's awesome to have working aarch64 builds of the Swift toolchain, especially the Swift for TensorFlow one.

In the latest Swift for TensorFlow builds, libtensorflow and libtensorflow_framework have been missing from the packaging. I believe this can be fixed by adding 

```
install-tensorflow
```

to the build-presets.ini patch. I tested this out on my Jetson Xavier here, and it does seem to cause the libraries to be copied over into the right place.

Also, I was successfully able to enable CUDA support for the Jetson devices, but I don't know if that's something you'd like to have in the broader patch repository. It may only enable GPU support for these devices, because I'm not sure of CUDA support on other aarch64 hardware.

To do this, I added the following to /tensorflow/third_party/gpus/crosstool/CROSSTOOL.tpl (not sure if this part is needed, actually):

```
default_toolchain {
  cpu: "aarch64"
  toolchain_identifier: "local_linux"
}
```

and I inserted the aarch64 line here in /tensorflow/third_party/gpus/crosstool/BUILD.tpl:

```
cc_toolchain_suite(
    name = "toolchain",
    toolchains = {
        ...
        "aarch64": ":cc-compiler-local",
    },
)
```

Switching the patched area in build-presets.ini from `enable-tensorflow` to `enable-tensorflow-gpu` then should enable building a CUDA-compatible Swift for TensorFlow toolchain on at least the Jetson devices. Again, not sure if you'd want a pull request formulated for this because it may not be relevant for non-Jetson devices.

**Comment by futurejones** [comment]
@BradLarson Thanks for the info it is very helpful. 
If you can provide a patch for the CUDU support on the Jetson devices that would be great.
GPU support was next on the todo list and I have a Jetson Nano on order so I will be able to do some on device testing soon.

**Comment by futurejones** [comment]
I have updated the `build_presets` patch to allow for the use of the `tensorflow_linux` presets.  
Presets available are:  
`tensorflow_linux`  
`tensorflow_linux,no_test`  
`tensorflow_linux,gpu`  
`tensorflow_linux,gpu,no_test`
I suggest using the `no_test` options as not all the tests are passing at the moment.
