### ISSUE TITLE
raspbian 64 install error

### ISSUE THREAD

**Issue by hdcola** [futurejones/swift-arm64#6]
I use https://www.raspberrypi.org/forums/viewtopic.php?f=117&t=275370 provided for 64-bit operating systems. This problem occurred during installation.

I'm a raspberry pi 3B.

```
The following packages have unmet dependencies:
 swift5:armhf : Depends: clang:armhf but it is not going to be installed
                Depends: python2.7-dev:armhf but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by futurejones** [comment]
It looks like you are trying to install an armhf (32bit) version of Swift.
The 64bit Raspberry Pi OS is built on top of the 64bit version of Debian 10 Buster so you need packages built for Debian 10 not Raspbian. 
The easiest way to install Swift is to use the Swift-Arm package repository.
https://packagecloud.io/swift-arm/release/packages/debian/buster/swift-lang_5.2.4-8-debian-buster_arm64.deb

Step 1 - Install the repository.
```
curl -s https://packagecloud.io/install/repositories/swift-arm/release/script.deb.sh | sudo bash
```
Step 2 - Install Swift
```
sudo apt-get install swift-lang
```
Note: The install packages are now named `swift-lang` from version 5.2.4

**Comment by hdcola** [comment]
After your note, I have a feeling it's a raspbian 64-bit beta issue. Let's wait for it to fix the related bugs. Thanks.
