### ISSUE TITLE
Build for Manjaro/Arch

### ISSUE THREAD

**Issue by theironrobin** [futurejones/swift-arm64#8]
How can I build for Manjaro or Arch?

**Comment by futurejones** [comment]
@alexr4535 Sorry I can't help you with Manjaro or Arch. 
I know that @soloturn is successfully building swift for x86_64 on arch, details are here - https://github.com/soloturn/swift-aur so building on arm64/arch should also be possible providing all the dependancies are available in aarch64/arm64 versions.

**Comment by soloturn** [comment]
a working arch aur PKGBUILD is here: https://aur.archlinux.org/packages/swift-language-git/. challenges were similar to https://github.com/termux/termux-packages/tree/master/packages, @buttaface was so kind to upstream his patches so it should build out of the box.

**Comment by buttaface** [comment]
I don't believe my Android AArch64 patches are used when building for linux AArch64, so you will probably have to apply both the patches from this repo and the Arch package to get it to build.
