### ISSUE TITLE
is it possible to run vscode with sourcekit-lsp?

### ISSUE THREAD

**Issue by carlhung** [futurejones/swift-arm64#9]
I tried to use sourcekit-lsp with vscode.
I can do it on my x86 ubuntu. but can't make it work on my pi4 with ubuntu 20.04 64bit.

**Comment by futurejones** [comment]
@carlhung Yes it should be possible. I have tested sourcekit-lsp and the sourcekit-lsp-vscode extension without any problems on the following systems:-
Raspberry Pi 4 4GB
1. RaspiOS / Debian Buster (beta)64bit - Swift version 5.3.1 - VSCode version 1.51.1
2. Ubuntu 20.04 Focal - Swift version 5.3.1 - VSCode version 1.51.1
3. Ubuntu 20.10 Groovy - Swift version 5.3.1 - VSCode version 1.51.1

Can you give some info on the problems you are having?

**Comment by carlhung** [comment]
oh. yes. i reinstalled again. it works. thx.
